<?php if ($posts = $this->getRecent()): ?>

    <div class="widget-latest">

        <div class="title"><?php echo Mage::helper('blog')->__('Latest Posts'); ?></div>

        <ul id="blog-slider" class="owl-carousal">

            <?php foreach ($posts as $post): ?>

                <li class="blog-home item">
                <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
               
                
                <?php $html_content = substr($post->getPostContent(),0,380);
$html_content = Mage::helper('cms')->getPageTemplateProcessor()->filter($html_content);
echo $html_content; echo "&nbsp; {...}";?>
                   
<!--                    <a class="button" href="<? /* php echo $post->getAddress(); ?>" ><?php echo "READ MORE" */?></a>-->
                    <a class="readm" href="<?php echo $post->getAddress(); ?>" ><?php echo "Read more" ?></a>
<!--                    <a class="" href="#">READ MORE</a>        -->
                </li>

            <?php endforeach; ?>

        </ul>

    </div>

<?php endif; ?>


<script type="text/javascript">
    jQuery.noConflict();
    jQuery(document).ready(function() {
 
  jQuery("#blog-slider").owlCarousel({
 
      autoPlay: 5000, //Set AutoPlay to 3 seconds
 
      items : 1,
      itemsDesktop : [1199,1],
      itemsDesktopSmall : [979,1]
 
  });
 
});
</script>