<?php
	// Detalle de una noticia
?>
	<div class="box cNoticias">
		<div class="boxFndPie">
			<div class="head">
				<h1><?php echo $this->__('News Blog')?></h1>
			</div>
			<div class="cNoticia">
				<?php $news = $this->getLoadedNewsCollection(); ?>
			<?php if($news){ ?>
			
			<h4><?php echo $news['title'] ?></h4>
			
			<div style="float:right;width:200px;margin:10px;margin-right:0px;border:1px solid #e4e4e4;">			
				<ins style="display:inline-table;border:none;height:100px;margin:0;padding:0;position:relative;visibility:visible;width:100%;">
					<ins style="display:block;border:none;height:100px;margin:0;padding:0;position:relative;visibility:visible;"><?php 
			
					if($news['filename']){
					
					$dire = $news['filename'];
					?>
					<img src="<?php echo $dire; ?>" width="100%" height="100" alt="<?php echo $news['filename']; ?>" title="<?php echo $news['title']; ?>"  />
				<?php
				}
				?>
					</ins>
				</ins>
			</div>
		<p><?php echo nl2br($news['texto']) ?></p>
		<?php }else{ ?>
		<p class="msgNoResultados"><?php echo $this->__("At this moment there is no available information in this section. Please, try again in the next days.") ?></p>
<?php } ?>
			</div>
		</div>
	</div>
	
	 		<div class="buttons-set">
                  <span class="f-left"> <a href="<?php echo $this->getUrl('news/listado') ?>"><?php echo $this->__('Back') ?></a></span>
			</div>
		

