<div class="box cNoticias">
	<div class="boxFndPie">
		<div class="head">
			<h1><?php echo $this->__('News Blog') ?></h1>
		</div>
		<div class="cuerpo">
			<?php $news = $this->getLoadedNewsCollection();?>
			<?php if($news->getSize() > 0) : ?>
			<?php echo $this->getToolbarHtml(); ?>
			<?php foreach ($news as $noticia): ?>
			<div class="noticia">
				<div class="content">
					<h4><a href="<?php echo $this->getUrl('news/detalle', array('id' => $noticia->getId().'/'.$noticia->getAmigable().'.html')) ?>"><?php echo $noticia->getTitle() ?></a></h4>
					<p class="cBreve"><?php echo nl2br(Mage::helper('core/string')->truncate($noticia->getTexto(),160)); ?></p>
					<p class="news_more"><span ><a href="<?php echo $this->getUrl('news/detalle', array('id' => $noticia->getId().'/'.$noticia->getAmigable().'.html')) ?>"><?php echo $this->__('Read more')?></a></span></p>
				</div>
				<div class="image">
					<?php if($noticia->getFilename()) : ?>
						<?php  
						$dire = $noticia->getFilename();?>
						<img src="<?php echo $dire; ?>" width="100%" alt="<?php echo $noticia->getFilename(); ?>" title="<?php echo $noticia->getTitle(); ?>"  />
					<?php endif;?>	
				</div>
			</div>
			<?php endforeach; ?>
			
			<?php else : ?>
			<p class="msgNoResultados"><?php echo $this->__("At this moment there is no available information in this section. Please, try again in the next days.") ?></p>
			<?php endif;?>
		</div>
	</div>
</div>

