<div class="header-menu mobile">


<div class="left-nav-mobilei collapse" id="nav-mobilei">


    
<ul id="left-nav-mobile" class="">
<li   class="level0 nav-1  level-top   first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-mats" class="level-top" style="">
        <span style="">Yoga Mats</span>
         
    </a>

    
    </li><li   class="level0 nav-1  level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-bolsters" class="level-top" style="">
        <span style="">Bolsters</span>
         
    </a>

    
    </li><li   class="level0 nav-1 parent level-top">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props" class="level-top" style="">
        <span style="">Props</span>
         
    </a>

            <ul class="level0 ">
            <li  class="level1 nav-2 parent    first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-bolsters" class="" style="">
        <span style="">Yoga Bolsters</span>
         
    </a>

            <ul class="level1 ">
            <li  class="level2 nav-3     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-bolsters/bolsters/" class="" style="">
        <span style="">Bolsters</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-bolsters/yoga-cushions" class="" style="">
        <span style="">Yoga Cushions</span>
         
    </a>

    
    </li><li  class="level2 nav-3     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-bolsters/replacement-covers" class="" style="">
        <span style="">Replacement Covers</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li  class="level1 nav-2 parent   ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-blocks" class="" style="">
        <span style="">Yoga Blocks</span>
         
    </a>

            <ul class="level1 ">
            <li  class="level2 nav-3     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-blocks/foam-blocks" class="" style="">
        <span style="">Foam Blocks</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-blocks/wood-blocks" class="" style="">
        <span style="">Wood Blocks</span>
         
    </a>

    
    </li><li  class="level2 nav-3     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-blocks/yoga-rollers" class="" style="">
        <span style="">Yoga Rollers</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-blankets" class="" style="">
        <span style="">Yoga Blankets</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-ropes-inversion-props" class="" style="">
        <span style="">Yoga Ropes</span>
         
    </a>

    
    </li><li  class="level1 nav-2 parent   ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-chairs" class="" style="">
        <span style="">Yoga Chairs</span>
         
    </a>

            <ul class="level1 ">
            <li  class="level2 nav-3     first last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-benger" class="" style="">
        <span style="">Yoga Benger</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-belts" class="" style="">
        <span style="">Yoga Belts</span>
         
    </a>

    
    </li><li  class="level1 nav-2 parent   ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props" class="" style="">
        <span style="">Wooden Props</span>
         
    </a>

            <ul class="level1 ">
            <li  class="level2 nav-3     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/multi-function-prop" class="" style="">
        <span style="">Yoga Barrel</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/backbend-bench" class="" style="">
        <span style="">Backbender</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/yoga-tressler/" class="" style="">
        <span style="">Yoga Tressler</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/yoga-headstander" class="" style="">
        <span style="">Yoga Headstander</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/slanting-plank" class="" style="">
        <span style="">Slanting Plank</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/halasana-benches" class="" style="">
        <span style="">Kapotasana Extension</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/viparita-karani-box" class="" style="">
        <span style="">Viparita Karani Box</span>
         
    </a>

    
    </li><li  class="level2 nav-3     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/wooden-yoga-props/meditation-stool" class="" style="">
        <span style="">Meditation Stool</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li  class="level1 nav-2     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-organic-range" class="" style="">
        <span style="">Organic Range</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li   class="level0 nav-1  level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-kits" class="level-top" style="">
        <span style="">Kits</span>
         
    </a>

    
    </li><li   class="level0 nav-1 parent level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories" class="level-top" style="">
        <span style="">Accessories</span>
         
    </a>

            <ul class="level0 ">
            <li  class="level1 nav-2     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/yoga-mat-bags" class="" style="">
        <span style="">Yoga Mat Bags</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-props/yoga-bolsters/replacement-covers" class="" style="">
        <span style="">Bolster Covers</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/eye-wrap-bandage" class="" style="">
        <span style="">Eye Wrap Bandage</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/yoga-eye-pillows" class="" style="">
        <span style="">Yoga Eye Pillows</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/yoga-sandbags" class="" style="">
        <span style="">Yoga Sandbags</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/yoga-timer" class="" style="">
        <span style="">Yoga Timer</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/yoga-towels" class="" style="">
        <span style="">Yoga Towels</span>
         
    </a>

    
    </li><li  class="level1 nav-2     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/yoga-accessories/therapy" class="" style="">
        <span style="">Therapy</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li   class="level0 nav-1 parent level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av" class="level-top" style="">
        <span style="">Books A/V</span>
         
    </a>

            <ul class="level0 ">
            <li  class="level1 nav-2 parent    first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds" class="" style="">
        <span style="">Yoga DVD's & CD's</span>
         
    </a>

            <ul class="level1 ">
            <li  class="level2 nav-3     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/home-practice-resources" class="" style="">
        <span style="">Home Practice Resources</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/new-to-iyogaprops" class="" style="">
        <span style="">New to IYOGAPROPS</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/audio-and-music-cds" class="" style="">
        <span style="">Audio & Music CDs</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/general-yoga" class="" style="">
        <span style="">General Yoga</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/beginners-yoga" class="" style="">
        <span style="">Beginners Yoga</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/pregnancy" class="" style="">
        <span style="">Pregnancy Yoga</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/ashtanga-flow" class="" style="">
        <span style="">Ashtanga / Flow</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/special-interest" class="" style="">
        <span style="">Special Interest</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/meditation-and-restorative" class="" style="">
        <span style="">Meditation & Restorative</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/kids-and-yoga" class="" style="">
        <span style="">Kids & Yoga</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/history-and-philosophy" class="" style="">
        <span style="">History & Philosophy</span>
         
    </a>

    
    </li><li  class="level2 nav-3     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-dvds-cds/iyengar-yoga" class="" style="">
        <span style="">Iyengar Yoga</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li  class="level1 nav-2 parent   ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books" class="" style="">
        <span style="">Yoga Books</span>
         
    </a>

            <ul class="level1 ">
            <li  class="level2 nav-3     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/new-to-iyogaprops" class="" style="">
        <span style="">New to IYOGAPROPS</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/all-titles" class="" style="">
        <span style="">All titles</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/general-titles" class="" style="">
        <span style="">General Titles</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/asana-pranayama" class="" style="">
        <span style="">Asana & Pranayama</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/women-yoga" class="" style="">
        <span style="">Women & Yoga</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/teaching-therapy" class="" style="">
        <span style="">Teaching & Therapy</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/history-philosophy" class="" style="">
        <span style="">History & Philosophy</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/kids-yoga" class="" style="">
        <span style="">Kids & Yoga</span>
         
    </a>

    
    </li><li  class="level2 nav-3    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/iyengar-books" class="" style="">
        <span style="">Iyengar Books</span>
         
    </a>

    
    </li><li  class="level2 nav-3     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/books-av/yoga-books/iyengar-institute-books" class="" style="">
        <span style="">Iyengar Institute Books</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li  class="level1 nav-2     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>retail/gift-voucher/iyogaprops-gift-voucher" class="" style="">
        <span style="">Gift Voucher</span>
         
    </a>

    
    </li>        </ul>
    
    </li><li   class="level0 nav-1 parent level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products" class="level-top" style="">
        <span style="">Wholesale</span>
         
    </a>

            <ul class="level0 ">
            <li  class="level1 nav-2     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/yoga-mats-wholesale" class="" style="">
        <span style="">Yoga Mats</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/blocks-belts-wholesale" class="" style="">
        <span style="">Blocks & Belts</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/yoga-bolsters-soft-support-wholesale" class="" style="">
        <span style="">Yoga Bolsters & Soft Support</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/ropes-inversion-props-wholesale" class="" style="">
        <span style="">Ropes & Inversion Props</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/chairs-backbenders-wholesale" class="" style="">
        <span style="">Chairs & Backbenders</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/wooden-props-wholesale" class="" style="">
        <span style="">Wooden Props</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/yoga-mat-bags-accesories-wholesale" class="" style="">
        <span style="">Yoga Mat Bags & Accessories</span>
         
    </a>

    
    </li><li  class="level1 nav-2     last">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-yoga-products/books-wholesale" class="" style="">
        <span style="">Books</span>
         
    </a>

    
    </li>        </ul>
    
    </li>
        <li   class="level0 nav-1 parent level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>gift" class="level-top" style="">
        <span style="">Gift</span>
         
    </a>
                    </li>
                    
    <li   class="level0 nav-1 parent level-top  ">
    <a href="<?php echo Mage::getBaseUrl(); ?>about-us" class="level-top" style="">
        <span style="">About</span>
         
    </a>

            <ul class="level0 ">
            <li  class="level1 nav-2     first">
    <a href="<?php echo Mage::getBaseUrl(); ?>why-shop-with-us" class="" style="">
        <span style="">Why shop with us</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>how-to-order" class="" style="">
        <span style="">How To Order</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="/testimonials" class="" style="">
        <span style="">Testimonials</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>wholesale-and-discounts" class="" style="">
        <span style="">Wholesale & Discounts</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>faq" class="" style="">
        <span style="">FAQ</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>certification" class="" style="">
        <span style="">Certification</span>
         
    </a>

    
    </li><li  class="level1 nav-2    ">
    <a href="<?php echo Mage::getBaseUrl(); ?>downloadable-products" class="" style="">
        <span style="">Downloadable Products</span>
         
    </a>

    
    </li><li  class="level1 nav-2     last">
    <a href="/contacts" class="" style="">
        <span style="">Contact</span>
         
    </a>

    
    </li>        </ul>
    
    </li></ul>
    </div>
    </div>
    
    
    <script type="text/javascript">
//<![CDATA[

var counter = 0;
jQuery("#left-nav-mobile ul.level0 li.parent").each(function () {
    counter++;
    var self = jQuery(this);
    self.addClass("submenu_" + counter);   
});

var counter = 0;
jQuery("#left-nav-mobile li.nav-1.parent").each(function () {
    counter++;
    var self = jQuery(this);
    self.addClass("dropzone" + counter);   
});
jQuery("#left-nav-mobile li.nav-1.parent").each(function () {
    counter++;
    var self = jQuery(this);
    self.addClass("dropzone");   
});

jQuery("#left-nav-mobile .dropzone ul").each(function () {
    counter++;
    var self = jQuery(this);
    self.addClass("submenu_drop" + counter);   
});


jQuery("#left-nav-mobile .dropzone").prepend('<span class="expandtop"></span>');
jQuery("#left-nav-mobile .dropzone a.subnew").removeAttr("href");
jQuery("#left-nav-mobile .dropzone ul").addClass("drop");
jQuery("#left-nav-mobile .dropzone a").addClass("subnew"); 
jQuery("#left-nav-mobile .dropzone ul a").removeClass("subnew"); 

jQuery("#left-nav-mobile ul.level0").addClass("show-sub");
  
jQuery("#left-nav-mobile .show-sub li.parent a").addClass("sub"); 
jQuery("#left-nav-mobile .show-sub li.parent ul a").removeClass("sub"); 
jQuery("#left-nav-mobile ul.level0 ul").addClass("drop");
jQuery("#left-nav-mobile .show-sub li.parent").prepend('<span class="expand"></span>');
jQuery("#left-nav-mobile .show-sub li.parent a.sub").removeAttr("href");

//DROPZONE 1//

jQuery('#left-nav-mobile .dropzone1 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone1 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone1 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone1 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone1 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone1 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	
	//DROPZONE 2//
	
	jQuery('#left-nav-mobile .dropzone2 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone2 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone2 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone2 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone2 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone2 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	
	//DROPZONE 2//
	
	jQuery('#left-nav-mobile .dropzone3 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone3 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone3 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone3 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone3.show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone3 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	
	//DROPZONE 2//
	
	jQuery('#left-nav-mobile .dropzone4 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone4 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone4 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone4 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone4 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone4 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	
	//DROPZONE 2//
	
	jQuery('#left-nav-mobile .dropzone5 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone5 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone5 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone5 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone5 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone5 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	
	//DROPZONE 2//
	
	jQuery('#left-nav-mobile .dropzone6 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone6 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone6 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone6 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone6 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone6 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	//DROPZONE 2//
	
	jQuery('#left-nav-mobile .dropzone7 .expandtop').on('click', function(e) { 
	  jQuery("#left-nav-mobile .dropzone7 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone7 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .dropzone7 a.subnew').on('click', function(e) {
     jQuery("#left-nav-mobile .dropzone7 .show-sub").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .dropzone7 .expandtop").toggleClass("activetop");
      e.preventDefault();
    });


//]]>

</script>



<script> 
jQuery.noConflict();  
   
   jQuery('#left-nav-mobile .submenu_1 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_1 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_1 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_1 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_1 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_1 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_2 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_2 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_2 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_2 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_2 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_2 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_3 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_3 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_3 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_3 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_3 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_3 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_4 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_4 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_4 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_4 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_4 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_4 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_5 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_5 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_5 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_5 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_5 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_5 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_6 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_6 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_6 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_6 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_6 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_6 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_7 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_7 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_7 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_7 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_7 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_7 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_8 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_8 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_8 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_8 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_8 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_8 .expand").toggleClass("active");
      e.preventDefault();
    });
	
	//DROP 2 Starts//
	
	jQuery('#left-nav-mobile .submenu_9 .expand').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_9 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_9 .expand").toggleClass("active");
      e.preventDefault();
    });
	 jQuery('#left-nav-mobile .submenu_9 a.sub').on('click', function(e) {
     //jQuery('.#left-nav-mobile .show-sub .drop').toggleClass("collapsed pressed"); //you can list several class names 
	  jQuery("#left-nav-mobile .submenu_9 .drop").toggleClass("dropnew");
	  jQuery("#left-nav-mobile .submenu_9 .expand").toggleClass("active");
      e.preventDefault();
    });
</script>

<style>
#left-nav-mobile .expand {
    cursor: pointer;
    float: left;
    width: 18px;
	height:23px;
	background: url('<?php echo $this->getSkinUrl(); ?>images/tiny-arrow-down.png');
}
#left-nav-mobile .activetop {background: url('<?php echo $this->getSkinUrl(); ?>images/tiny-arrow-up.png');}
#left-nav-mobile .expandtop {
    cursor: pointer;
    float: left;
    width: 18px;
	height:23px;
	background: url('<?php echo $this->getSkinUrl(); ?>images/tiny-arrow-down.png');
}
#left-nav-mobile .show-sub {
    padding-left: 15px;
}
#left-nav-mobile .active {background: url('<?php echo $this->getSkinUrl(); ?>images/tiny-arrow-up.png');}
#left-nav-mobile ul.show-sub li a {
    color: #898a8a;
    font-size: 14px;
    padding-left: 25px;
    text-decoration: none;
}
#left-nav-mobile .dropnew { display:block !important;}
#left-nav-mobile .drop { display:none;}
#left-nav-mobile a.subnew { font-weight:600; text-transform:uppercase; color:#666767; padding-left: 7px; cursor:pointer;}
#left-nav-mobile .show-sub a.sub { font-weight:600; text-transform:uppercase; color:#666767; padding-left: 7px; cursor:pointer;}
#left-nav-mobile .drop li a { font-size:14px; text-transform:none; font-weight:normal;}
#left-nav-mobile li a:hover {color:#8cc63e !important;}
#left-nav-mobile li.dropzone a {padding-left: 7px;}

</style>